create database mappet;
use mappet;

CREATE TABLE animal1(
CPF VARCHAR(11) PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
RACA VARCHAR(50) NOT NULL,
IDADE VARCHAR(20) NOT NULL,
LOCAL VARCHAR(20) NOT NULL,
FOTO LONGBLOB
);